
import fsx from "fs-extra";
import mustache from "mustache";

const generator = require("../../package.json");

// disabling escape
mustache.escape = s => s

export const BANNER = `/**
* @generated by ${ generator.name }:${ generator.version }, do not modify manually!
*/`

type Options = { format?: boolean }

export function render<Context = {}>(
  template: string,
  context: Context,
  options?: Options,
): string {
  const content = mustache.render(template, context)
  return options?.format
    ? content.replace(/^\s*[\r\n]/gm, "")
    : content
}

export function renderToFile<Context = {}>(
  file: string,
  template: string,
  context: Context,
  options?: Options,
): Promise<void> {
  return fsx.outputFile(
    file,
    render(template, context, options),
    "utf8"
  )
}

